//
//  Dictionary+Serializable.swift
//  BestSellerBooks
//
//  Created by Sedrak Igityan on 2/14/20.
//  Copyright © 2020 Sedrak Igityan. All rights reserved.
//

import Foundation


// MARK: - Json Error -

struct JsonSerializationError: Error {
    var localizedDescription: String = "Json converted failed"
}


// MARK: - Extension Data -

extension Data {
    /// Creates a response serializer that returns a JSON object result type constructed from the response data using
    /// `JSONSerialization` with the specified reading options.
    ///
    /// - parameter options: The JSON serialization reading options. Defaults to `.allowFragments`.
    ///
    /// - returns: A JSON object response serializer.
    public func toJson(options: JSONSerialization.ReadingOptions = .allowFragments) -> [String: Any] {

        do {
            let jsonResult = try JSONSerialization.jsonObject(with: self, options: options) // Create dict.
                
            guard let dict = jsonResult as? [String: Any] else { // Check if dict exist
                throw JsonSerializationError() // See JsonSerializationError
            }
                
            return dict
        } catch { // If JSONSerialization.jsonObject failed. error is autogenerated variable
            debugPrint("--- Error happened when wanted to serialize to json \(error.localizedDescription) ---")
            
            return [:] // `IF error happened function return empty --`
        }
    }
}
